### ISSUE TITLE
"adb push" invocation copies data to subdirectory

### ISSUE THREAD

**Issue by genpfault** [joshuabragge/twrp-manual-restore#1]
This line:

```
adb push $localpackages$package $remotepackages$package
```

...ends up creating duplicate subdirectories in the target data dir if the 'base' app-named directory already exists (which it should because you're supposed to install the APK before use):

```
/data/data/org.fedorahosted.freeotp/org.fedorahosted.freeotp/<data bits>
```

Stripping off the final `$package` fixes it for me:

```
adb push $localpackages$package $remotepackages
````

**Comment by joshuabragge** [comment]
Good catch - thanks for letting me know!
