### ISSUE TITLE
Feature request: Force-stop & clear data before restore

### ISSUE THREAD

**Issue by genpfault** [joshuabragge/twrp-manual-restore#2]
Something like this before the main `adb push` line:

    ...
    printf "=========================================================\n"
    printf "Killing %s\n" $package
    adb shell am force-stop $package
    printf "Clearing %s\n" $package
    adb shell pm clear $package
    printf "Restoring %s\n" $package
    ...

**Comment by joshuabragge** [comment]
Good idea - thanks!
